# This is a basic workflow to help you get started with Actions

name: CI to drone_app

# Controls when the action will run. written by harvey
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  musala_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn -f ./pom.xml clean package -Dmaven.test.skip=true

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: harveyimama/musala-drone-service:latest
          no-cache: true
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}